/* ============================================================
   atlas_ryu.js — frame atlas + animation table for RYU.

   The fighter's logical state is mapped to an animation, and each
   animation is a sequence of cells on the sprite sheet. Two profiles
   are supported:

     • "baked"  — a uniform grid generated by `npm run bake` from the
                  in-engine renderer (assets/ryu.png). Works out of the
                  box and proves the whole sprite path end to end.

     • "source" — coordinates describing a hand-authored sheet laid out
                  like the supplied RYU reference (an ANIMATIONS table,
                  SPECIAL MOVES rows, etc). Drop your PNG in as
                  assets/ryu.png, set ACTIVE = "source", and fine-tune
                  with the in-game calibration overlay (press O).

   Every animation maps to ONE skeleton pose function + a phase range
   so the same spec drives both the baker and the runtime.
   ============================================================ */
(function (global) {
  "use strict";
  const FP = global.FP, U = FP.U;

  // ---- which fighter state uses which animation -------------------
  // key  : atlas animation name
  // anim : skeleton pose function (js/skeleton.js  FP.Skeleton.A[...])
  // n    : number of frames to bake / sample
  // fps  : playback speed     loop : looping?
  const SPEC = [
    { key: "idle",      anim: "idle",       n: 4,  fps: 8,  loop: true },
    { key: "walk",      anim: "walkF",      n: 6,  fps: 12, loop: true },
    { key: "walkb",     anim: "walkB",      n: 6,  fps: 12, loop: true },
    { key: "dash",      anim: "dash",       n: 4,  fps: 18, loop: false },
    { key: "crouch",    anim: "crouch",     n: 2,  fps: 8,  loop: false },
    { key: "jump",      anim: "jump",       n: 4,  fps: 12, loop: false },
    { key: "block",     anim: "block",      n: 1,  fps: 6,  loop: false },
    { key: "blocklow",  anim: "blockLow",   n: 1,  fps: 6,  loop: false },
    { key: "lp",        anim: "lp",         n: 3,  fps: 18, loop: false },
    { key: "mp",        anim: "mp",         n: 4,  fps: 18, loop: false },
    { key: "hp",        anim: "hp",         n: 4,  fps: 16, loop: false },
    { key: "lk",        anim: "lk",         n: 3,  fps: 18, loop: false },
    { key: "mk",        anim: "mk",         n: 4,  fps: 18, loop: false },
    { key: "hk",        anim: "hk",         n: 4,  fps: 16, loop: false },
    { key: "clp",       anim: "crouchPunch",n: 3,  fps: 18, loop: false },
    { key: "clk",       anim: "crouchKick", n: 3,  fps: 18, loop: false },
    { key: "chk",       anim: "crouchKick", n: 3,  fps: 16, loop: false },
    { key: "jp",        anim: "jumpPunch",  n: 2,  fps: 12, loop: false },
    { key: "jk",        anim: "jumpKick",   n: 2,  fps: 12, loop: false },
    { key: "fireball",  anim: "fireball",   n: 5,  fps: 16, loop: false },
    { key: "dp",        anim: "dp",         n: 5,  fps: 16, loop: false },
    { key: "spin",      anim: "spinKick",   n: 4,  fps: 16, loop: false },
    { key: "super",     anim: "super",      n: 5,  fps: 14, loop: false },
    { key: "hurthigh",  anim: "hurtHigh",   n: 2,  fps: 10, loop: false },
    { key: "hurtlow",   anim: "hurtLow",    n: 2,  fps: 10, loop: false },
    { key: "knockdown", anim: "knockdown",  n: 4,  fps: 12, loop: false },
    { key: "getup",     anim: "getup",      n: 3,  fps: 12, loop: false },
    { key: "throw",     anim: "throw",      n: 3,  fps: 14, loop: false },
    { key: "victory",   anim: "victory",    n: 4,  fps: 8,  loop: true  },
    { key: "intro",     anim: "intro",      n: 3,  fps: 10, loop: false },
  ];

  // ---- baked uniform grid -----------------------------------------
  // generous cells so rising uppercuts / extended kicks never clip
  const CW = 190, CH = 300, COLS = 8, FOOT_MARGIN = 20;

  function buildBaked() {
    const cells = [];      // {anim, phase}
    const anims = {};
    for (const s of SPEC) {
      const idxs = [];
      for (let i = 0; i < s.n; i++) {
        const phase = s.loop ? i / s.n : (s.n === 1 ? 0.5 : i / (s.n - 1));
        idxs.push(cells.length);
        cells.push({ anim: s.anim, phase });
      }
      anims[s.key] = { cells: idxs, fps: s.fps, loop: s.loop };
    }
    const rows = Math.ceil(cells.length / COLS);
    return {
      name: "baked", cw: CW, ch: CH, cols: COLS, rows, footMargin: FOOT_MARGIN,
      sheetW: COLS * CW, sheetH: rows * CH, cells, anims,
      rect(index) {
        const c = index % COLS, r = (index / COLS) | 0;
        return { x: c * CW, y: r * CH, w: CW, h: CH, ax: CW / 2, ay: CH - FOOT_MARGIN };
      },
    };
  }

  /* ---- "source" profile: describe a hand-drawn reference sheet ----
     These rectangles assume a sheet laid out like the RYU reference:
     an ANIMATIONS table of small cells. They are best-effort starting
     points — open the calibration overlay (O) to nudge them onto your
     own artwork, then read the adjusted numbers from the console. */
  function buildSource() {
    // ANIMATIONS table geometry (tweak to match your PNG)
    const T = { x0: 305, y0: 32, cellW: 165, cellH: 92, cols: 6, gapY: 8 };
    // each table cell holds a few mini-poses; we sub-slice horizontally
    const cellSub = (col, row, sub, subCount) => {
      const cw = T.cellW / subCount;
      return {
        x: T.x0 + col * T.cellW + sub * cw, y: T.y0 + row * (T.cellH + T.gapY),
        w: cw, h: T.cellH, ax: cw / 2, ay: T.cellH - 6,
      };
    };
    // map atlas keys -> (col,row,subCount) in the reference table
    const tbl = {
      idle: [0, 0, 2], walk: [1, 0, 3], dash: [2, 0, 2], jump: [3, 0, 3], crouch: [4, 0, 1], block: [5, 0, 1],
      lp: [0, 1, 2], mp: [1, 1, 2], hp: [2, 1, 2], lk: [3, 1, 2], mk: [4, 1, 2], hk: [5, 1, 2],
      clp: [0, 2, 2], clk: [1, 2, 2], jp: [2, 2, 2], jk: [3, 2, 2], blocklow: [4, 2, 1], jumpland: [5, 2, 1],
      throw: [0, 3, 2], throwtech: [1, 3, 2], hurthigh: [2, 3, 2], hurtmid: [3, 3, 2], hurtlow: [4, 3, 2], knockdown: [5, 3, 2],
      getup: [0, 4, 2], techback: [1, 4, 2], techfwd: [2, 4, 2], recovery: [3, 4, 1], victory: [5, 4, 1],
    };
    const cells = []; const anims = {};
    for (const key in tbl) {
      const [col, row, sub] = tbl[key];
      const idxs = [];
      for (let i = 0; i < sub; i++) { idxs.push(cells.length); cells.push({ rect: cellSub(col, row, i, sub) }); }
      anims[key] = { cells: idxs, fps: 10, loop: key === "idle" || key === "walk" || key === "victory" };
    }
    return {
      name: "source", explicit: true, cells, anims,
      rect(index) { return cells[index].rect; },
    };
  }

  // map a fighter -> atlas animation key
  function animFor(f) {
    const st = f.state;
    if (st === "attack" || st === "special" || st === "super") {
      const a = f.attack && f.attack.move && f.attack.move.anim;
      const m = {
        lp: "lp", mp: "mp", hp: "hp", lk: "lk", mk: "mk", hk: "hk",
        crouchPunch: "clp", crouchKick: "clk", jumpPunch: "jp", jumpKick: "jk",
        fireball: "fireball", dp: "dp", spinKick: "spin", super: "super",
      };
      return m[a] || "idle";
    }
    const map = {
      idle: "idle", walkF: "walk", walkB: "walkb", dash: "dash", crouch: "crouch",
      jump: "jump", block: "block", blockLow: "blocklow",
      hurt: "hurthigh", hurtCrouch: "hurtlow", hurtAir: "hurthigh",
      knockdown: "knockdown", getup: "getup", throwStart: "throw",
      victory: "victory", intro: "intro", ko: "knockdown",
    };
    return map[st] || "idle";
  }

  const profiles = { baked: buildBaked(), source: buildSource() };
  const Atlas = {
    profiles,
    ACTIVE: "baked",
    get current() { return this.profiles[this.ACTIVE]; },
    animFor,
    SPEC, CW, CH, COLS, FOOT_MARGIN,
    // resolve the rect for a fighter's current animation frame
    frameRectFor(f) {
      const prof = this.current;
      const key = animFor(f);
      const a = prof.anims[key] || prof.anims.idle;
      if (!a) return null;
      const t = (f.spriteT || 0);
      const fcount = a.cells.length;
      let fi;
      if (a.loop) fi = Math.floor(t * a.fps) % fcount;
      else fi = Math.min(fcount - 1, Math.floor(t * a.fps));
      return prof.rect(a.cells[fi]);
    },
  };

  FP.AtlasRyu = Atlas;
})(window);
